#ifndef APP_NUS_DATA_H__
#define APP_NUS_DATA_H__

#define BLE_DATA_HEAD_ID			0
#define BLE_DATA_HEAD_OP_KEY		1
#define BLE_DATA_HEAD_LENGTH		2

#define BLE_OP_KEY_SET				0x01
#define BLE_OP_KEY_GET				0x02
#define BLE_OP_KEY_ACK				0x03
#define BLE_OP_KEY_RESULT			0x04

#define BLE_ID_GET_STEP_INFO		0x01
#define BLE_ID_GET_BP				0x03
#define BLE_ID_GET_TEMPERATURE		0x08
#define BLE_ID_SET_VIBTATION		0x0A
#define BLE_ID_GET_BLE_FLASH_DATA	0x40
#define BLE_ID_GET_SENSOR_RAWDATA	0x41
#define BLE_ID_SET_SYSTEM_TIME		0x60
#define BLE_ID_SET_USER_INFO		0x62
#define BLE_ID_DUF_MODE				0x64
#define BLE_ID_GET_VERSION_NUMER	0x65
#define BLE_ID_GET_SERIAL_NUMER		0x66
#define BLE_ID_FACTORY_G_TEST		0x84
#define BLE_ID_GET_TEMPERATURE_ADC	0x90
#define BLE_ID_GET_BOOT_VER_NUM		0x91

#endif
